general:
  assetBaseDir: config/assets
  primaryLanguage: de
  secondaryLanguage: en
  description:
    # The following strings utilize special UTF-8 spacing characters
    # that might not be displayed correctly in all text editors.
    en: |+
      Can you create a circular
      smartphone economy?

    de: |-
      Kannst du eine
      Kreislaufwirtschaft
      für  Handys  aufbauen?
  scoreLabels:
    circularity:
      en: Circularity
      de: Kreislauf
    coverage:
      de: Bedarf gedeckt
      en: Demand met
  autoReset:
    timeoutSeconds: 10
    condition: |-
      Object.values(stocks).reduce(
        (acc, stockValue) => acc || stockValue > variables.phoneGoal * 30,
        false,
      )
    title:
      de: Du hast die Wirtschaft zerschmettert!
      en: You crashed the economy!
    description:
      de: Spiel startet neu.
      en: Restarting game.
