interaction:
  actionCardDelayMs: 1000
  assets:
    markerSlotActive:
      url: slots/marker-slot-active_x-121_y-121.webp
    markerSlotInactive:
      url: slots/marker-slot-inactive_x-121_y-121.webp
  slotGroups:
    - id: technology
      type: action-card
      slots:
        - markerSlot: { id: technology-ms-1, x: 188.7, y: 1318.22, angle: 0 }
          cardSlot: { id: technology-cs-1, x: 600, y: 1200, angle: 90 }
        - markerSlot: { id: technology-ms-2, x: 188.7, y: 1064.51, angle: 0 }
          cardSlot: { id: technology-cs-2, x: 600, y: 945, angle: 90 }
        - markerSlot: { id: technology-ms-3, x: 188.7, y: 810.8, angle: 0 }
          cardSlot: { id: technology-cs-3, x: 600, y: 690, angle: 90 }
      cards:
        - parameterTransformId: (T) Triple Diamantglas
          url: cards/technology/triple-diamond-glass.webp
        - parameterTransformId: (T) KI-Automatisierung
          url: cards/technology/ai-automation.webp
        - parameterTransformId: (T) Modular smartphone
          url: cards/technology/modular-smartphone.webp
        - parameterTransformId: (T) Planed Obsol
          url: cards/technology/planned-obsolescence.webp
        - parameterTransformId: (T) Software Upgrade
          url: cards/technology/software-upgrade.webp
    - id: policy
      type: action-card
      slots:
        - markerSlot: { id: policy-ms-1, x: 1368.6, y: 2008.4, angle: 0 }
          cardSlot: { id: policy-cs-1, x: 1250, y: 1600, angle: 0 }
        - markerSlot: { id: policy-ms-2, x: 1624.3, y: 2008.4, angle: 0 }
          cardSlot: { id: policy-cs-2, x: 1510, y: 1600, angle: 0 }
        - markerSlot: { id: policy-ms-3, x: 1876.4, y: 2008.4, angle: 0 }
          cardSlot: { id: policy-cs-3, x: 1770, y: 1600, angle: 0 }
      cards:
        - parameterTransformId: (P) Schul-Repair-Café
          url: cards/policy/school-repair-cafe.webp
        - parameterTransformId: (P) Extreme Öko-Steuer
          url: cards/policy/extreme-eco-tax.webp
        - parameterTransformId: (P) Handy-Abo
          url: cards/policy/handy-abo.webp
        - parameterTransformId: (P) Recycle-Prämie
          url: cards/policy/recycle-bonus.webp
        - parameterTransformId: (P) Wartungsvertrag
          url: cards/policy/wartungsvertrag.webp
        - parameterTransformId: (P) Jugendschutz
          url: cards/policy/youth-protection.webp
        - parameterTransformId: (P) Ein-Telefon-Gesetz
          url: cards/policy/one-phone-law.webp
        - parameterTransformId: (P) BYOD
          url: cards/policy/byod.webp
        - parameterTransformId: (P) Handy Detox Day
          url: cards/policy/handy-detox-day.webp
    - id: event
      type: event-card
      minDelayMs: 1000
      maxDelayMs: 2000
      minDurationMs: 5000
      maxDurationMs: 10000
      markerSlot: { id: event-ms, x: 2066.8, y: 154.8, angle: 0 }
      cardSlots:
        - { id: event-cs-1, x: 1650, y: 60, angle: 0 }
        - { id: event-cs-2, x: 1400, y: 60, angle: 0 }
        - { id: event-cs-3, x: 1150, y: 60, angle: 0 }
      cards:
        - parameterTransformId: (E) Weltweite Chip-Krise
          url: cards/event/global-chip-crisis.webp
        - parameterTransformId: (E) Neues Ananas Phone
          url: cards/event/new-pineapple-phone.webp
        - parameterTransformId: (E) Sicherheitslücke
          url: cards/event/security-gap.webp
        - parameterTransformId: (E) Transport Streik
          url: cards/event/transportstreik.webp
        - parameterTransformId: (E) Deponie Streik
          url: cards/event/landfill-strike.webp
    - id: reduce
      type: basic
      slots:
        - { id: reduce-1, x: 1576.4, y: 1232.8, angle: 0 }
        - { id: reduce-2, x: 1830.8, y: 1244.8, angle: 0 }
        - { id: reduce-3, x: 2082.8, y: 1256.8, angle: 0 }
      parameterTransformIds: [reduce, reduce, reduce]
    - id: reuse
      type: basic
      slots:
        - { id: reuse-1, x: 3512, y: 1392, angle: 0 }
        - { id: reuse-2, x: 3502.4, y: 1136.8, angle: 0 }
        - { id: reuse-3, x: 3492.8, y: 884.8, angle: 0 }
      parameterTransformIds: [reuse, reuse, reuse]
    - id: repair
      type: basic
      slots:
        - { id: repair-1, x: 1304.4, y: 842.8, angle: 0 }
        - { id: repair-2, x: 1556.8, y: 804.8, angle: 0 }
        - { id: repair-3, x: 1806, y: 768, angle: 0 }
      parameterTransformIds: [repair, repair, repair]
    - id: refurbish
      type: basic
      slots:
        - { id: refurbish-1, x: 2958.8, y: 2000.8, angle: 0 }
        - { id: refurbish-2, x: 3192.8, y: 1898, angle: 0 }
        - { id: refurbish-3, x: 3424, y: 1796.8, angle: 0 }
      parameterTransformIds: [refurbish, refurbish, refurbish]
    - id: recycle
      type: basic
      slots:
        - { id: recycle-1, x: 464.8, y: 442.8, angle: 0 }
        - { id: recycle-2, x: 691, y: 326, angle: 0 }
        - { id: recycle-3, x: 916, y: 210.8, angle: 0 }
      parameterTransformIds: [recycle, recycle, recycle]
