interaction:
  slotActivationDelay: 1
  slotDeactivationDelay: 1
  slotGroups:
    - id: technology
      type: action-card
      slots:
        - {
            id: technology-1,
            x: 188.7,
            y: 1318.22,
            angle: 0,
            card: { x: 0, y: 0, angle: 0 },
          }
        - {
            id: technology-2,
            x: 188.7,
            y: 1064.51,
            angle: 0,
            card: { x: 0, y: 0, angle: 0 },
          }
        - {
            id: technology-3,
            x: 188.7,
            y: 810.8,
            angle: 0,
            card: { x: 0, y: 0, angle: 0 },
          }
      cards:
        - parameterTransformId: technology-card-1
          url: technology-card-1.png
          title:
            en: 'T-Tech-en-1'
            de: 'T-Tech-de-1'
          description:
            en: 'D-Tech-en-1'
            de: 'D-Tech-de-1'
        - parameterTransformId: technology-card-2
          url: technology-card-2.png
          title:
            en: 'T-Tech-en-2'
            de: 'T-Tech-de-2'
          description:
            en: 'D-Tech-en-2'
            de: 'D-Tech-de-2'
        - parameterTransformId: technology-card-3
          url: technology-card-3.png
          title:
            en: 'T-Tech-en-3'
            de: 'T-Tech-de-3'
          description:
            en: 'D-Tech-en-3'
            de: 'D-Tech-de-3'
        - parameterTransformId: technology-card-4
          url: technology-card-4.png
          title:
            en: 'T-Tech-en-4'
            de: 'T-Tech-de-4'
          description:
            en: 'D-Tech-en-4'
            de: 'D-Tech-de-4'
    - id: policy
      type: action-card
      slots:
        - id: policy-1
          x: 1368.6
          y: 2008.4
          angle: 0
          card: { x: 0, y: 0, angle: 0 }
        - id: policy-2
          x: 1624.3
          y: 2008.4
          card: { x: 0, y: 0, angle: 0 }
        - id: policy-3
          x: 1876.4
          y: 2008.4
          angle: 0
          card: { x: 0, y: 0, angle: 0 }
      cards:
        - parameterTransformId: policy-card-1
          url: policy-card-1.png
          title:
            en: 'T-Pol-en-1'
            de: 'T-Pol-de-1'
          description:
            en: 'D-Pol-en-1'
            de: 'D-Pol-de-1'
        - parameterTransformId: policy-card-2
          url: policy-card-2.png
          title:
            en: 'T-Pol-en-2'
            de: 'T-Pol-de-2'
          description:
            en: 'D-Pol-en-2'
            de: 'D-Pol-de-2'
        - parameterTransformId: policy-card-3
          url: policy-card-3.png
          title:
            en: 'T-Pol-en-3'
            de: 'T-Pol-de-3'
          description:
            en: 'D-Pol-en-3'
            de: 'D-Pol-de-3'
        - parameterTransformId: policy-card-4
          url: policy-card-4.png
          title:
            en: 'T-Pol-en-4'
            de: 'T-Pol-de-4'
          description:
            en: 'D-Pol-en-4'
            de: 'D-Pol-de-4'
    - id: event
      type: event-card
      slots:
        - id: event
          x: 2066.8
          y: 154.8
          angle: 0
          card: { x: 0, y: 0, angle: 0 }
      cards:
        - parameterTransformId: event-card-1
          url: event-card-1.png
          title:
            en: 'T-Ev-en-1'
            de: 'T-Ev-de-1'
          description:
            en: 'D-Ev-en-1'
            de: 'D-Ev-de-1'
        - parameterTransformId: event-card-2
          url: event-card-2.png
          title:
            en: 'T-Ev-en-2'
            de: 'T-Ev-de-2'
          description:
            en: 'D-Ev-en-2'
            de: 'D-Ev-de-2'
        - parameterTransformId: event-card-3
          url: event-card-3.png
          title:
            en: 'T-Ev-en-3'
            de: 'T-Ev-de-3'
          description:
            en: 'D-Ev-en-3'
            de: 'D-Ev-de-3'
        - parameterTransformId: event-card-4
          url: event-card-4.png
          title:
            en: 'T-Ev-en-4'
            de: 'T-Ev-de-4'
          description:
            en: 'D-Ev-en-4'
            de: 'D-Ev-de-4'
    - id: reduce
      type: basic
      slots:
        - { id: reduce-1, x: 1576.4, y: 1232.8, angle: 0 }
        - { id: reduce-2, x: 1830.8, y: 1244.8, angle: 0 }
        - { id: reduce-3, x: 2082.8, y: 1256.8, angle: 0 }
      parameterTransformIds: [reduce, reduce, reduce]
    - id: reuse
      type: basic
      slots:
        - { id: reuse-1, x: 3512, y: 1392, angle: 0 }
        - { id: reuse-2, x: 3502.4, y: 1136.8, angle: 0 }
        - { id: reuse-3, x: 3492.8, y: 884.8, angle: 0 }
      parameterTransformIds: [reuse, reuse, reuse]
    - id: repair
      type: basic
      slots:
        - { id: repair-1, x: 1304.4, y: 842.8, angle: 0 }
        - { id: repair-2, x: 1556.8, y: 804.8, angle: 0 }
        - { id: repair-3, x: 1806, y: 768, angle: 0 }
      parameterTransformIds: [repair, repair, repair]
    - id: refurbish
      type: basic
      slots:
        - { id: refurbish-1, x: 2958.8, y: 2000.8, angle: 0 }
        - { id: refurbish-2, x: 3192.8, y: 1898, angle: 0 }
        - { id: refurbish-3, x: 3424, y: 1796.8, angle: 0 }
      parameterTransformIds: [refurbish, refurbish, refurbish]
    - id: recycle
      type: basic
      slots:
        - { id: recycle-1, x: 464.8, y: 442.8, angle: 0 }
        - { id: recycle-2, x: 691, y: 326, angle: 0 }
        - { id: recycle-3, x: 916, y: 210.8, angle: 0 }
      parameterTransformIds: [recycle, recycle, recycle]
