model:
  initialStocks:
    capacityOfNewlyProducedPhones: 0
    capacityOfRecycledMaterials: 0
    capacityOfRefurbishedPhones: 0
    capacityOfRepairedPhones: 0
    phonesInUse: 0
    supplyOfBrokenPhones: 0
    supplyOfDisposedPhones: 0
    supplyOfHibernatingPhones: 0
    supplyOfNewlyProducedPhones: 0
    supplyOfRecycledMaterials: 0
    supplyOfRefurbishedPhones: 0
    supplyOfRepairedPhones: 0
  initialParameters:
    abandonExcessRate: 0.5
    abandonRate: 0.3
    acquireRate: 1
    breakRate: 0.25
    capacityAdjustmentRate: 0.1
    disposeIncentive: 0.90
    disposeRate: 1
    landfillIncentive: 0.85
    landfillRate: 1
    naturalResourcesIncentive: 0.85
    newPhoneProductionRate: 1
    newlyProducedPhoneIncentive: 0.85
    numberOfUsers: 1000000
    phonesPerUserGoal: 1.5
    recycleRate: 0.7
    recyclingIncentive: 0.15
    refurbishmentIncentive: 0.05
    refurbishmentRate: 0.8
    repairIncentive: 0.05
    repairRate: 0.9
    reuseIncentive: 0.05
