parameterTransforms:
  - id: reduce
    script: |-
      phonesPerUserGoal *= 0.9;
      landfillIncentive *= 0.6;
      naturalResourcesIncentive *= 0.6;
  - id: reuse
    script: reuseIncentive *= 3;
  - id: repair
    script: |-
      repairIncentive *= 1.75;
      repairRate *= 1.75;
  - id: refurbish
    script: |-
      refurbishmentIncentive *= 1.75;
      refurbishmentRate *= 1.75;
  - id: recycle
    script: |-
      recyclingIncentive *= 1.3;
      recycleRate *= 1.3;
  - id: (T) Triple Diamantglas
    script: breakRate *= 0.1;
  - id: (T) KI-Automatisierung
    script: |-
      newPhoneProductionRate *=5;
      recycleRate *=3;
      refurbishmentRate *=3;
      repairRate *=3;
  - id: (T) Modular smartphone
    script: |-
      repairIncentive *= 3;
      refurbishmentIncentive *= 5;
      refurbishmentRate *=2;
      disposeIncentive *=0.7;
  - id: (T) Planed Obsol
    script: |-
      newPhoneProductionRate *=3;
      breakRate *= 9;
      refurbishmentRate *= 0.5;
      refurbishmentIncentive *= 0.5;
      repairIncentive *= 0.2;
      repairRate *= 0.5;
      reuseIncentive *= 0.5;
      disposeIncentive *= 5;
      disposeRate *= 2;
      acquireRate *=2
  - id: (T) Software Upgrade
    script: |-
      newPhoneProductionRate *= 0.9;
      newlyProducedPhoneIncentive *= 0.8;
      disposeIncentive *=0.5;
      disposeRate *= 0.5;
      reuseIncentive *= 5;
      abandonRate *= 0.5;
  - id: (P) Schul-Repair-Café
    script: |-
      repairIncentive *= 3;
      repairRate *= 2;
      disposeIncentive *= 0.5;
      disposeRate *= 0.5;
      newlyProducedPhoneIncentive *= 0.5;
  - id: (P) Extreme Öko-Steuer
    script: |-
      landfillIncentive *= 0.1;
      naturalResourcesIncentive *= 0.1;
  - id: (P) Handy-Abo
    script: |-
      abandonRate *= 5;
      newPhoneProductionRate *= 2;
      newlyProducedPhoneIncentive *= 10;
      acquireRate *= 2;
      disposeIncentive *= 3;
      disposeRate *= 2;
  - id: (P) Recycle-Prämie
    script: |-
      abandonRate *= 0.8;
      newPhoneProductionRate *= 2;
      newlyProducedPhoneIncentive *= 5;
      refurbishmentIncentive *= 0.7;
      recyclingIncentive *= 3;
      repairIncentive *= 0.7;
      reuseIncentive *= 0.7;
  - id: (P) Wartungsvertrag
    script: |-
      abandonRate *= 0.5;
      abandonExcessRate *= 0.5;
      newlyProducedPhoneIncentive *= 0.5;
      repairIncentive *= 5;
      repairRate *= 2;
      disposeRate *= 0.8;
      disposeIncentive *= 0.8;
  - id: (P) Jugendschutz
    script: |-
      acquireRate *= 0.9;
      newPhoneProductionRate *=0.9;
      phonesPerUserGoal *= 0.8;
  - id: (P) Ein-Telefon-Gesetz
    script: |-
      phonesPerUserGoal *= 0.2;
      newPhoneProductionRate *= 0.5;
      newlyProducedPhoneIncentive *= 0.5;
      abandonRate *= 0.1;
      landfillIncentive *= 0.5;
      naturalResourcesIncentive *= 0.5;
  - id: (P) BYOD
    script: |-
      phonesPerUserGoal *= 0.8;
      newlyProducedPhoneIncentive *= 0.8;
      abandonRate *= 0.5;
      landfillIncentive *= 0.5;
      naturalResourcesIncentive *= 0.5;
  - id: (P) Handy Detox Day
    script: |-
      landfillIncentive *= 0.5;
      naturalResourcesIncentive *= 0.5;
      newPhoneProductionRate *=0.9;
      disposeIncentive *=0.8;
      newlyProducedPhoneIncentive *= 0.8;
      phonesPerUserGoal *= 0.8;
  - id: (E) Weltweite Chip-Krise
    script: |-
      naturalResourcesIncentive *=0.01;
      newPhoneProductionRate *= 1;
  - id: (E) Neues Ananas Phone
    script: |-
      abandonRate *= 3;
      newPhoneProductionRate *= 2;
      newlyProducedPhoneIncentive *= 10;
      acquireRate *= 2;
      landfillIncentive *= 1.5;
      naturalResourcesIncentive *= 1.5;
  - id: (E) Sicherheitslücke
    script: |-
      abandonExcessRate *=5;
      abandonRate *=5;
      disposeIncentive *=5;
      disposeRate *=5;
      newlyProducedPhoneIncentive *=15;
      reuseIncentive *= 0.2;
  - id: (E) Transport Streik
    script: |-
      landfillRate *= 0.1; 
      recycleRate *= 0.1; 
      repairRate *= 0.1;
      refurbishmentRate *= 0.1; 
      acquireRate *= 0.1; 
      disposeRate *= 0.1; 
      newPhoneProductionRate *=0.1; 
      reuseIncentive *= 5; 
      disposeIncentive *=0.5; 
      landfillRate *= 0.1;
  - id: (E) Deponie Streik
    script: |-
      landfillRate *= 0.055;
