triggers:
  - id: test-1
    events:
      - condition:
          'some condition based on the model elements (stocks, flows etc)'
        url: 'url to the image'
      - condition:
          'some condition based on the model elements (stocks, flows etc)'
        url: 'url to the image'
      - condition:
          'some condition based on the model elements (stocks, flows etc)'
        url: 'url to the image'
  - id: test-2
    events:
      - condition:
          'some condition based on the model elements (stocks, flows etc)'
        url: 'url to the image'
      - condition:
          'some condition based on the model elements (stocks, flows etc)'
        url: 'url to the image'
      - condition:
          'some condition based on the model elements (stocks, flows etc)'
        url: 'url to the image'
