triggers:
  - id: background
    events:
      - condition: 'true'
        url: 'background_x0_y0.webp'
  - id: government
    events:
      - condition: 'parameters.breakRate > 0.5 /* just for testing */'
        url: 'government_static_x794_y1705.webp'
